sudo: required
services:
  - docker

before_install:
  - docker build -t /Users/dong/Documents/react-test/ -f Dockerfile.dev .

script:
  - docker run /Users/dong/Documents/react-test/ npm run test -- --coverage