sudo: required
services:
  - docker

before_install:
  - docker build -t hyoungdong/docker-react -f Dockerfile.dev .

script:
  - docker run CI=true hyoungdong/docker-react npm run test -- --coverage

after_success:
    - echo "Test success"