sudo: required
services:
  - docker

before_install:
  - docker build -t hyoungdong/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hyoungdong/docker-react npm run test -- --coverage

after_success:
    - echo "Test success"

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-160277033502"
  bucket-path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
